/*
  DO NOT IMPORT PAGE COMPONENTS HERE: WILL CAUSE CYCLIC LOOPS
  note: consumed by <AppRoot>
 */
export default [
  {
    name: 'rules',
    exact: true,
    path: '/',
    meta: {
      title: 'Kammy: Fantasy Football',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Rules',
    requiresAuthentication: false,
    component: 'RulesPage',
    template: 'default',
  },
  {
    name: 'cup',
    exact: true,
    path: '/cup',
    meta: {
      title: 'Kammy: Fantasy Football',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Cup',
    requiresAuthentication: false,
    component: 'Cup',
    template: 'default',
  },
  {
    name: 'premierLeague-teams',
    exact: true,
    path: '/premier-league/teams',
    meta: {
      title: 'Kammy - Premier League Teams',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Teams',
    requiresAuthentication: false,
    component: 'PremierLeagueTeams',
    template: 'default',
  },
  {
    name: 'premierLeague-rankings',
    exact: true,
    path: '/premier-league/rankings',
    meta: {
      title: 'Kammy - Premier League Rankings',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      division: 'premierLeague',
    },
    label: 'League Table',
    requiresAuthentication: false,
    component: 'PremierLeagueRankings',
    template: 'default',
  },
  {
    name: 'premierLeague-players',
    exact: true,
    path: '/premier-league/players/',
    meta: {
      title: 'Kammy Admin - premier-league Players',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      division: 'premierLeague',
    },
    label: 'Players',
    requiresAuthentication: false,
    component: 'PremierLeaguePlayersPage',
    template: 'default',
  },
  {
    name: 'premierLeague-transfers',
    exact: true,
    path: '/premier-league/transfers/',
    meta: {
      title: 'Kammy premier-league - Transfers',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Transfers',
    props: {
      division: 'premierLeague',
    },
    requiresAuthentication: false,
    component: 'TransfersPage',
    template: 'default',
  },
  {
    name: 'premierLeague-draft',
    exact: true,
    path: '/premier-league/draft/',
    meta: {
      title: 'Kammy premier-league - Draft',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Draft',
    props: {
      division: 'premierLeague',
    },
    requiresAuthentication: false,
    component: 'PremierLeagueDraftPage',
    template: 'default',
  },
  {
    name: 'championship-teams',
    exact: true,
    path: '/championship/teams',
    meta: {
      title: 'Kammy - Championship Teams',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Teams',
    requiresAuthentication: false,
    component: 'ChampionshipTeams',
    template: 'default',
  },
  {
    name: 'championship-rankings',
    exact: true,
    path: '/championship/rankings',
    meta: {
      title: 'Kammy - Championship Rankings',
      description: 'Kammy : Fantasy Football',
    },
    label: 'League Table',
    requiresAuthentication: false,
    component: 'ChampionshipRankings',
    template: 'default',
  },
  {
    name: 'championship-players',
    exact: true,
    path: '/championship/players/',
    meta: {
      title: 'Kammy Admin - championship Players',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Players',
    requiresAuthentication: false,
    component: 'ChampionshipPlayersPage',
    template: 'default',
  },
  {
    name: 'championship-transfers',
    exact: true,
    path: '/championship/transfers/',
    meta: {
      title: 'Kammy Championship - Transfers',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Transfers',
    props: {
      division: 'championship',
    },
    requiresAuthentication: false,
    component: 'TransfersPage',
    template: 'default',
  },
  {
    name: 'championship-draft',
    exact: true,
    path: '/championship/draft/',
    meta: {
      title: 'Kammy championship - Draft',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Draft',
    props: {
      division: 'championship',
    },
    requiresAuthentication: false,
    component: 'ChampionshipDraftPage',
    template: 'default',
  },
  {
    name: 'leagueOne-teams',
    exact: true,
    path: '/league-one/teams',
    meta: {
      title: 'Kammy - League One Teams',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      division: 'leagueOne',
    },
    label: 'Teams',
    requiresAuthentication: false,
    component: 'LeagueOneTeams',
    template: 'default',
  },
  {
    name: 'leagueOne-rankings',
    exact: true,
    path: '/league-one/rankings',
    meta: {
      title: 'Kammy - League One Rankings',
      description: 'Kammy : Fantasy Football',
    },
    label: 'League Table',
    requiresAuthentication: false,
    component: 'LeagueOneRankings',
    template: 'default',
  },
  {
    name: 'leagueOne-players',
    exact: true,
    path: '/league-one/players/',
    meta: {
      title: 'Kammy Admin - league-one Players',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      division: 'leagueOne',
    },
    label: 'Players',
    requiresAuthentication: false,
    component: 'LeagueOnePlayersPage',
    template: 'default',
  },
  {
    name: 'leagueOne-transfers',
    exact: true,
    path: '/league-one/transfers/',
    meta: {
      title: 'Kammy League One - Transfers',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Transfers',
    props: {
      division: 'leagueOne',
    },
    requiresAuthentication: false,
    component: 'TransfersPage',
    template: 'default',
  },
  {
    name: 'leagueOne-draft',
    exact: true,
    path: '/league-one/draft/',
    meta: {
      title: 'Kammy league-one - Draft',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Draft',
    props: {
      division: 'leagueOne',
    },
    requiresAuthentication: false,
    component: 'LeagueOneDraftPage',
    template: 'default',
  },
  {
    name: 'admin-players',
    exact: true,
    path: '/admin/players/',
    meta: {
      title: 'Kammy Admin - Admin Players',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Players',
    requiresAuthentication: false,
    component: 'AdminPlayersPage',
    template: 'default',
  },
  {
    name: 'admin',
    exact: true,
    path: '/admin/',
    meta: {
      title: 'Kammy Admin - Admin Homepage',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Admin',
    requiresAuthentication: false,
    component: 'AdminHomepage',
    template: 'default',
  },
  {
    name: 'admin-cup',
    exact: true,
    path: '/admin/cup/',
    meta: {
      title: 'Kammy Admin - Admin Cup',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Cup',
    requiresAuthentication: false,
    component: 'AdminCup',
    template: 'default',
  },
];
