/*
  DO NOT IMPORT PAGE COMPONENTS HERE: WILL CAUSE CYCLIC LOOPS
  note: consumed by <AppRoot>
 */
export default [
  {
    name: 'rules',
    exact: true,
    path: '/',
    meta: {
      title: 'Kammy: Fantasy Football',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      src: 'https://docs.google.com/document/d/e/2PACX-1vTFlrJtsgbHsNScMLEDyAy1KnSclQmghRXLMdZV7T3L0phP2gp4r71GCzaAGPs6Z4kyw8UvyhD3axmr/pub',
    },
    label: 'Rules',
    requiresAuthentication: false,
    component: 'iFrame',
    template: 'default',
  },
  {
    name: 'cup',
    exact: true,
    path: '/cup',
    meta: {
      title: 'Kammy: Fantasy Football',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Cup',
    requiresAuthentication: false,
    component: 'Cup',
    template: 'default',
  },
  {
    name: 'premierLeague-teams',
    exact: true,
    path: '/premier-league/teams',
    meta: {
      title: 'Kammy - Premier League Teams',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      divisionId: 'premierLeague',
      label: 'Premier League: Teams',
    },
    label: 'Teams',
    requiresAuthentication: false,
    component: 'TeamsPage',
    template: 'default',
  },
  {
    name: 'premierLeague-rankings',
    exact: true,
    path: '/premier-league/rankings',
    meta: {
      title: 'Kammy - Premier League Rankings',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      label: 'Premier League: League Table',
      divisionId: 'premierLeague',
    },
    label: 'League Table',
    requiresAuthentication: false,
    component: 'DivisionRankings',
    template: 'default',
  },
  {
    name: 'premierLeague-players',
    exact: true,
    path: '/premier-league/players/',
    meta: {
      title: 'Kammy Admin - premier-league Players',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      division: 'PremierLeague',
    },
    label: 'Players',
    requiresAuthentication: false,
    component: 'PlayersPage',
    template: 'default',
  },
  {
    name: 'premierLeague-transfers',
    exact: true,
    path: '/premier-league/transfers/',
    meta: {
      title: 'Kammy premier-league - Transfers',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Transfers',
    props: {
      division: 'premierLeague',
    },
    requiresAuthentication: false,
    component: 'TransfersPage',
    template: 'default',
  },
  {
    name: 'premierLeague-draft',
    exact: true,
    path: '/premier-league/draft/',
    meta: {
      title: 'Kammy premier-league - Draft',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Draft',
    props: {
      division: 'premierLeague',
      src: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQr3amNkTAxhpVu1Y1fBhEqDCV0r6J3PBLuNpHlhvmoaJQ7UIfgcOgSd9YKGsTsQfdXzZOLCsJwHnAk/pubhtml?gid=0&single=true',
    },
    requiresAuthentication: false,
    component: 'iFrame',
    template: 'default',
  },
  {
    name: 'championship-teams',
    exact: true,
    path: '/championship/teams',
    meta: {
      title: 'Kammy - Championship Teams',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      label: 'League One: Teams',
      divisionId: 'leagueOne',
    },
    label: 'Teams',
    requiresAuthentication: false,
    component: 'TeamsPage',
    template: 'default',
  },
  {
    name: 'championship-rankings',
    exact: true,
    path: '/championship/rankings',
    meta: {
      title: 'Kammy - Championship Rankings',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      label: 'Championship: League Table',
      divisionId: 'championship',
    },
    label: 'League Table',
    requiresAuthentication: false,
    component: 'DivisionRankings',
    template: 'default',
  },
  {
    name: 'championship-players',
    exact: true,
    path: '/championship/players/',
    meta: {
      title: 'Kammy Admin - championship Players',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      division: 'Championship',
    },
    label: 'Players',
    requiresAuthentication: false,
    component: 'PlayersPage',
    template: 'default',
  },
  {
    name: 'championship-transfers',
    exact: true,
    path: '/championship/transfers/',
    meta: {
      title: 'Kammy Championship - Transfers',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Transfers',
    props: {
      division: 'championship',
    },
    requiresAuthentication: false,
    component: 'TransfersPage',
    template: 'default',
  },
  {
    name: 'championship-draft',
    exact: true,
    path: '/championship/draft/',
    meta: {
      title: 'Kammy championship - Draft',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Draft',
    props: {
      division: 'championship',
      src: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTLwqJA5bCMEeBr6N8IUQK-F2Cmx_-O-yBkp6JlnyKiuy08bPWyEEXSJa2ErJgS-OkcMkZgIZGntmB5/pubhtml?gid=0&single=true',
    },
    requiresAuthentication: false,
    component: 'iFrame',
    template: 'default',
  },
  {
    name: 'leagueOne-teams',
    exact: true,
    path: '/league-one/teams',
    meta: {
      title: 'Kammy - League One Teams',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      divisionId: 'leagueOne',
      label: 'League One: Teams',
    },
    label: 'Teams',
    requiresAuthentication: false,
    component: 'TeamsPage',
    template: 'default',
  },
  {
    name: 'leagueOne-rankings',
    exact: true,
    path: '/league-one/rankings',
    meta: {
      title: 'Kammy - League One Rankings',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      label: 'League One: League Table',
      divisionId: 'leagueOne',
    },
    label: 'League Table',
    requiresAuthentication: false,
    component: 'DivisionRankings',
    template: 'default',
  },
  {
    name: 'leagueOne-players',
    exact: true,
    path: '/league-one/players/',
    meta: {
      title: 'Kammy Admin - league-one Players',
      description: 'Kammy : Fantasy Football',
    },
    props: {
      division: 'LeagueOne',
    },
    label: 'Players',
    requiresAuthentication: false,
    component: 'PlayersPage',
    template: 'default',
  },
  {
    name: 'leagueOne-transfers',
    exact: true,
    path: '/league-one/transfers/',
    meta: {
      title: 'Kammy League One - Transfers',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Transfers',
    props: {
      division: 'leagueOne',
    },
    requiresAuthentication: false,
    component: 'TransfersPage',
    template: 'default',
  },
  {
    name: 'leagueOne-draft',
    exact: true,
    path: '/league-one/draft/',
    meta: {
      title: 'Kammy league-one - Draft',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Draft',
    props: {
      division: 'leagueOne',
      src: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTd7NQ2Iu4P7zzjwpHtHwLFacDKTwpmLO08R90fFdYurxEh-LJlYFGjoNM79sPi6iBpV3owLf7mXwOm/pubhtml?gid=0&single=true',
    },
    requiresAuthentication: false,
    component: 'iFrame',
    template: 'default',
  },
  {
    name: 'admin-players',
    exact: true,
    path: '/admin/players/',
    meta: {
      title: 'Kammy Admin - Admin Players',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Players',
    requiresAuthentication: false,
    component: 'AdminPlayersPage',
    template: 'default',
  },
  {
    name: 'admin',
    exact: true,
    path: '/admin/',
    meta: {
      title: 'Kammy Admin - Admin Homepage',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Admin',
    requiresAuthentication: false,
    component: 'AdminHomepage',
    template: 'default',
  },
  {
    name: 'admin-cup',
    exact: true,
    path: '/admin/cup/',
    meta: {
      title: 'Kammy Admin - Admin Cup',
      description: 'Kammy : Fantasy Football',
    },
    label: 'Cup',
    requiresAuthentication: false,
    component: 'AdminCup',
    template: 'default',
  },
];
