version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.9-jessie-browsers
    working_directory: ~/kammy-ui-workflow
    environment:
      TZ: "/usr/share/zoneinfo/Europe/London"
    steps:
      - checkout
  test:
    docker:
      - image: circleci/node:10.9-jessie-browsers
    working_directory: ~/kammy-ui-workflow
    steps:
      - checkout
      - run: yarn
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10.9-jessie-browsers
    working_directory: ~/kammy-ui-workflow
    environment:
      HEROKU_APP: kammy-ui
    steps:
      - checkout
      - run: git config --global user.name "Peter Mouland"
      - run: git config --global user.email "peter.mouland@gmail.com"
      - run: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master -f --no-verify

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
